// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	jwt "template/pkg/jwt"
)

// JWTService is an autogenerated mock type for the JWTService type
type JWTService struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: userId, isAdmin, roleID, email
func (_m *JWTService) GenerateToken(userId string, isAdmin bool, roleID int, email string) (string, error) {
	ret := _m.Called(userId, isAdmin, roleID, email)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, bool, int, string) string); ok {
		r0 = rf(userId, isAdmin, roleID, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, bool, int, string) error); ok {
		r1 = rf(userId, isAdmin, roleID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseToken provides a mock function with given fields: tokenString
func (_m *JWTService) ParseToken(tokenString string) (jwt.JwtCustomClaim, error) {
	ret := _m.Called(tokenString)

	var r0 jwt.JwtCustomClaim
	if rf, ok := ret.Get(0).(func(string) jwt.JwtCustomClaim); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(jwt.JwtCustomClaim)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseRefreshToken provides a mock function with given fields: tokenString
func (_m *JWTService) ParseRefreshToken(tokenString string) (jwt.JwtCustomClaim, error) {
	ret := _m.Called(tokenString)

	var r0 jwt.JwtCustomClaim
	if rf, ok := ret.Get(0).(func(string) jwt.JwtCustomClaim); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(jwt.JwtCustomClaim)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateTokenPair provides a mock function with given fields: userID, isAdmin, roleID, email
func (_m *JWTService) GenerateTokenPair(userID string, isAdmin bool, roleID int, email string) (jwt.TokenPair, error) {
	ret := _m.Called(userID, isAdmin, roleID, email)

	var r0 jwt.TokenPair
	if rf, ok := ret.Get(0).(func(string, bool, int, string) jwt.TokenPair); ok {
		r0 = rf(userID, isAdmin, roleID, email)
	} else {
		r0 = ret.Get(0).(jwt.TokenPair)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, bool, int, string) error); ok {
		r1 = rf(userID, isAdmin, roleID, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJWTService interface {
	mock.TestingT
	Cleanup(func())
}

// NewJWTService creates a new instance of JWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJWTService(t mockConstructorTestingTNewJWTService) *JWTService {
	mock := &JWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
