// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	"template/internal/business/domain"
)

// UserIntegrationRepository is an autogenerated mock type for the UserIntegrationRepository type
type UserIntegrationRepository struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: ctx, in
func (_m *UserIntegrationRepository) Upsert(ctx context.Context, in *domain.UserIntegration) (domain.UserIntegration, error) {
	ret := _m.Called(ctx, in)

	var r0 domain.UserIntegration
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserIntegration) domain.UserIntegration); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.UserIntegration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserIntegration) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *UserIntegrationRepository) ListByUser(ctx context.Context, userID string) ([]domain.UserIntegration, error) {
	ret := _m.Called(ctx, userID)

	var r0 []domain.UserIntegration
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.UserIntegration); ok {
		r0 = rf(ctx, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]domain.UserIntegration)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByUserAndProvider provides a mock function with given fields: ctx, userID, provider
func (_m *UserIntegrationRepository) DeleteByUserAndProvider(ctx context.Context, userID string, provider string) error {
	ret := _m.Called(ctx, userID, provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserIntegrationRepository creates a new instance of UserIntegrationRepository.
func NewUserIntegrationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserIntegrationRepository {
	m := &UserIntegrationRepository{}
	m.Mock.Test(t)

	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}
