// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	"template/internal/business/domain"
	repointerface "template/internal/datasources/repositories/interface"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// ChangeActiveUser provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) ChangeActiveUser(ctx context.Context, inDom *domain.User) error {
	ret := _m.Called(ctx, inDom)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEmail provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) GetByEmail(ctx context.Context, inDom *domain.User) (domain.User, error) {
	ret := _m.Called(ctx, inDom)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) domain.User); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, inDom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, inDom
func (_m *UserRepository) Store(ctx context.Context, inDom *domain.User) (domain.User, error) {
	ret := _m.Called(ctx, inDom)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) domain.User); ok {
		r0 = rf(ctx, inDom)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, inDom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetByID(ctx context.Context, id string) (domain.User, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *UserRepository) GetByGoogleSub(ctx context.Context, sub string) (domain.User, error) {
	ret := _m.Called(ctx, sub)
	return ret.Get(0).(domain.User), ret.Error(1)
}

func (_m *UserRepository) LinkGoogleAccount(ctx context.Context, userID string, acct domain.GoogleAccount) error {
	return _m.Called(ctx, userID, acct).Error(0)
}

func (_m *UserRepository) UnlinkGoogle(ctx context.Context, userID string) error {
	return _m.Called(ctx, userID).Error(0)
}

// List provides a mock function with given fields: ctx, filter, offset, limit
func (_m *UserRepository) List(ctx context.Context, filter repointerface.UserListFilter, offset int, limit int) ([]domain.User, error) {
	ret := _m.Called(ctx, filter, offset, limit)

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func(context.Context, repointerface.UserListFilter, int, int) []domain.User); ok {
		r0 = rf(ctx, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, repointerface.UserListFilter, int, int) error); ok {
		r1 = rf(ctx, filter, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAdmins provides a mock function with given fields: ctx
func (_m *UserRepository) ListAdmins(ctx context.Context) ([]domain.User, error) {
	ret := _m.Called(ctx)

	var r0 []domain.User
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePassword provides a mock function with given fields: ctx, in
func (_m *UserRepository) UpdatePassword(ctx context.Context, in *domain.User) error {
	ret := _m.Called(ctx, in)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDelete provides a mock function with given fields: ctx, id
func (_m *UserRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *UserRepository) UpdateRole(ctx context.Context, id string, roleID int) error {
	ret := _m.Called(ctx, id, roleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, id, roleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSignature provides a mock function with given fields: ctx, userID
func (_m *UserRepository) GetSignature(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)
	var r0 string
	if v, ok := ret.Get(0).(string); ok {
		r0 = v
	}
	return r0, ret.Error(1)
}

// SetSignature provides a mock function with given fields: ctx, userID, img
func (_m *UserRepository) SetSignature(ctx context.Context, userID string, img string) error {
	ret := _m.Called(ctx, userID, img)
	return ret.Error(0)
}

// SetLatinName provides a mock function with given fields: ctx, userID, firstEn, lastEn
func (_m *UserRepository) SetLatinName(ctx context.Context, userID string, firstEn string, lastEn string) error {
	ret := _m.Called(ctx, userID, firstEn, lastEn)
	return ret.Error(0)
}

// GetByNationalID provides a mock function with given fields: ctx, nationalID
func (_m *UserRepository) GetByNationalID(ctx context.Context, nationalID string) (domain.User, error) {
	ret := _m.Called(ctx, nationalID)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = rf(ctx, nationalID)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nationalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertFromEID provides a mock function with given fields: ctx, in
func (_m *UserRepository) UpsertFromEID(ctx context.Context, in *domain.User) (domain.User, error) {
	ret := _m.Called(ctx, in)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) domain.User); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertSuperAdmin provides a mock function with given fields: ctx, in, account
func (_m *UserRepository) UpsertSuperAdmin(ctx context.Context, in *domain.User, account *domain.SuperadminAccount) (domain.User, error) {
	ret := _m.Called(ctx, in, account)

	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, *domain.SuperadminAccount) domain.User); ok {
		r0 = rf(ctx, in, account)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, *domain.SuperadminAccount) error); ok {
		r1 = rf(ctx, in, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

func (_m *UserRepository) CreatePreRegistered(ctx context.Context, in *domain.User) (domain.User, error) {
	ret := _m.Called(ctx, in)
	var r0 domain.User
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) domain.User); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
