// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// Verifier is an autogenerated mock type for the verify.Sender type
type Verifier struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, to, channel
func (_m *Verifier) Send(ctx context.Context, to string, channel string) (string, error) {
	ret := _m.Called(ctx, to, channel)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, to, channel)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, to, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Check provides a mock function with given fields: ctx, requestID, code
func (_m *Verifier) Check(ctx context.Context, requestID string, code string) error {
	ret := _m.Called(ctx, requestID, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, requestID, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewVerifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewVerifier creates a new instance of Verifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVerifier(t mockConstructorTestingTNewVerifier) *Verifier {
	mock := &Verifier{}
	mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
